### ISSUE TITLE
graphql error: Resource not accessible by integration

### ISSUE THREAD

**Issue by ssbarnea** [sourcegraph/codenotify#19]
While trying to use this action I got into an error which seems bit unclear `graphql error: Resource not accessible by integration`, full log https://github.com/ansible/ansible-lint/runs/6450547152?check_suite_focus=true

My implementation is quite simple: https://github.com/ansible/ansible-lint/blob/main/.github/workflows/tox.yml#L260-L266 and as seen that is triggered by pull requests.

I supposed that the reason for getting this error is lack of permissions for adding a comment to a pull request? The README does not mention anything about such limitation.

Should I add a custom token, if so which permissions do I need to give it? That is bit problematic on pull request due to security concerns of leaking that token as I might not be able to use a secrets environment as pull request can be received from forks too.

References:
* https://github.community/t/message-resource-not-accessible-by-integration/176887

**Comment by nicksnyder** [comment]
I took a look at this and how action tokens/permissions have changed since I originally wrote this. I know what is going on here and will propose a docs update.
